apiVersion: v1
kind: Secret
metadata:
    name: bb-secrets
type: Opaque
stringData:
    db-user-var: root
    db-userpass-var: pass
    db-name-var: metalsdb
    db-host-var: mysql
    back-port-var: '8000'
    cbr-url-var: http://cbr.example.com/metals.xml
