apiVersion: v1
kind: Secret
metadata:
    name: bb-secrets
type: Opaque
stringData:
    db-user-var: root
    db-userpass-var: Lsadsafsa
    db-name-var: metalsdb
    db-host-var: mysqldb
    back-port-var: '8000'
    cbr-url-var: 'http://cbr-emulator/metals.xml'
