"""empty message

Revision ID: d0fbe78f0502
Revises: 
Create Date: 2022-04-17 21:28:41.646586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0fbe78f0502'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metals_codes',
    sa.Column('code', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('code'),
    sa.UniqueConstraint('code', 'name')
    )
    op.create_table('metals_data',
    sa.Column('dt', sa.Date(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.Integer(), nullable=False),
    sa.Column('buy', sa.Float(precision=10, asdecimal=2), nullable=True),
    sa.Column('sell', sa.Float(precision=10, asdecimal=2), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dt', 'code')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('metals_data')
    op.drop_table('metals_codes')
    # ### end Alembic commands ###
