apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitlab-runner-admin
  namespace: default
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: gitlab-runner-admin
rules:
  - apiGroups: [""]
    resources: ["*"]
    verbs: ["*"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gitlab-runner-admin
  namespace: default
subjects:
  - kind: ServiceAccount
    name: gitlab-runner-admin
    namespace: default
roleRef:
  kind: Role
  name: gitlab-runner-admin
  apiGroup: rbac.authorization.k8s.io
